### ISSUE TITLE
Audio is not paused after deleting

### ISSUE THREAD

**Issue by nitramek** [icechen1/BlackBox#1]
I think the title is pretty clear. 

I think you are already made a fix but as I looked through the code it could be enough to add in PlayerDialogFragment after line [143 ](https://github.com/icechen1/BlackBox/blob/47403a4f0385005c5d86b5916952115fa842b043/app/src/main/java/icechen1/com/blackbox/fragments/PlayerDialogFragment.java#L143)in the condition.
`AudioWife.getInstance.release();`

**Comment by yucombinator** [comment]
Thanks, fixed it! Will do some testing and include it in the next release.

**Comment by yucombinator** [comment]
Released!
