### ISSUE TITLE
Issue in building project - Missing resources in project

### ISSUE THREAD

**Issue by abhijeetpathak** [icechen1/BlackBox#2]
I get the following when compiling the project:

Error:(14, 22) No resource found that matches the given name (at 'ettIcon' with value '@drawable/ic_edit_grey_900_24dp').
Error:(15, 32) No resource found that matches the given name (at 'ettIconInEditMode' with value '@drawable/ic_done_grey_900_24dp').
Error:(79, 26) No resource found that matches the given name (at 'src' with value '@drawable/ic_play_arrow_black_36dp').
Error:(88, 26) No resource found that matches the given name (at 'src' with value '@drawable/ic_pause_black_36dp').
Error:(98, 26) No resource found that matches the given name (at 'src' with value '@drawable/ic_favorite_black_36dp').
Error:(107, 26) No resource found that matches the given name (at 'src' with value '@drawable/ic_favorite_outline_black_36dp').
Error:(117, 26) No resource found that matches the given name (at 'src' with value '@drawable/ic_share_grey_900_36dp').
Error:(126, 26) No resource found that matches the given name (at 'src' with value '@drawable/ic_delete_black_36dp').

**Comment by yucombinator** [comment]
Whoops, might have forgotten to check those in, it is pushed up in a new commit! Let me know if it works now.

**Comment by abhijeetpathak** [comment]
The issue is still there.

Also, one of the resource file is named 'Rewind_ori_portrait.png'. This will not work. Resource files must contain lower case letters only.

**Comment by yucombinator** [comment]
Hmm, weird, are you sure you are on the latest `master`? In https://github.com/icechen1/BlackBox/commit/678019ac90e32c45a6e38bf8ceb913e3e6e6edbb I have uncapitalized `Rewind` (see last change in the list).

**Comment by abhijeetpathak** [comment]
Builds fine now.
Closing the issue.
